---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-rollout-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - real.baeke.info
  http:
  - name: primary
#   - match:
#     - headers:
#         end-user:
#           exact: sathya
    route:
    - destination:
        host: istio-rollout-stable
      weight: 60
    - destination:
        host: istio-rollout-canary
      weight: 40
